In [1]:
import numpy as np

# 数组的形状 ndarray.shape 

In [3]:
t1 = np.arange(12)
print(t1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
print(t1.shape)

(12,)


In [6]:
t2 = np.array([[1,2,3],[4,5,6]])
print(t2)

[[1 2 3]
 [4 5 6]]


In [7]:
print(t2.shape)

(2, 3)


In [13]:
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
print(t3.shape)

(2, 2, 3)


# 修改数组形状ndarray.reshape(shape)

In [15]:
t4 = np.arange(12)
print(t4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
t4 = t4.reshape((3,4))
print(t4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
t5 = np.arange(24).reshape((2,3,4))
print(t5)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
t5 = t5.reshape((24,))  #转换为一维数组
print(t5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [20]:
#若不知到数组中元素个数，转换为一维数组的方法有

t5 = t5.flatten()  #flatten()函数会将二维数组扁平化，即压成一维形状
print(t5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# 数组计算

In [26]:
t6 = np.arange(24).reshape((4,6))
print(t6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [22]:
print(t6+2)

[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]]


In [23]:
print(t6*2)

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]


In [24]:
print(t6/2)

[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


In [27]:
t7 = np.arange(100,124).reshape((4,6))
print(t7)

[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]


In [29]:
print(t7+t6)

[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]


### 不同维度间的计算 

In [36]:
t8 = np.array([0,1,2,3,4,5])
print(t6-t8)
print(t6*t8)

[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]
[[  0   1   4   9  16  25]
 [  0   7  16  27  40  55]
 [  0  13  28  45  64  85]
 [  0  19  40  63  88 115]]


In [31]:
t9 = np.arange(4).reshape((4,1))
print(t9)

[[0]
 [1]
 [2]
 [3]]


In [37]:
print(t6-t9)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 对于多维数组/矩阵通过指定axis 参数，可以沿数组的指定轴进行操作

#### 对于二维数组来说
#### axis = 0表示沿着每一列或行标签\索引值向下执行方法
#### axis = 1表示沿着每一行或者列标签横向执行对应的方法


In [3]:
b = np.arange(12).reshape(3,4)
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
print(np.sum(b))  #np.sum是数组内所有元素的和，可以理解为b.sum()通过一个方向求和后，在接着求和

66


In [9]:
b[0][0] = 1
print(np.prod(b))  #数组内所有元素的积

39916800


In [41]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[12 15 18 21]
[ 6 22 38]


In [42]:
print(b.min(axis=0))
print(b.min(axis=1))

[0 1 2 3]
[0 4 8]
