In [2]:
import numpy as np


# 基本函数

In [9]:
a = np.arange(15).reshape(3,5)  #定义一个数组有15个元素，reshape(3,5)表示三行五列
print('a.shape:',a.shape)  #ndarray.shape---数组的维度,即n行m列   (3, 5)
print('a.ndim:',a.ndim)  #ndarray.ndim---数组维度的数量，n维数组       2
print('a.dtype:',a.dtype)  #ndarray.dtype---数组中对象元素的数据类型    int32
print('a.itemsize:',a.itemsize) #ndarray.itemsize---数组中每个元素的字节大小   4
print('a.size:',a.size) #ndarray.size---数组元素的总数      15
print(type(a)) #type(ndarray)---数组ndarray的类型     
 #<class 'numpy.ndarray'>


a.shape: (3, 5)
a.ndim: 2
a.dtype: int32
a.itemsize: 4
a.size: 15
<class 'numpy.ndarray'>


# np.array()

In [4]:
#使用numpy生成数组，得到ndarray类型的数组
t1 = np.array([1,2,3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
t2 = np.array(range(10))
print(t2)
print(type(t2))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
t3 = np.arange(1,12,2)  #相当于array(range(...))
print(t3)
print(type(t3))

[ 1  3  5  7  9 11]
<class 'numpy.ndarray'>


#  dtype(数组里面数据的类型)

In [8]:
print(t1.dtype)

int32


## 1.指定数据的类型

In [11]:

t4 = np.array(range(1,4),dtype=float)
print(t4)
print(type(t4))
print(t4.dtype)

[1. 2. 3.]
<class 'numpy.ndarray'>
float64


## 2.numpy中的bool类型 

In [12]:
t5 = np.array([1,0,1,0,0,1],dtype = bool)
print(t5)
print(t5.dtype)

[ True False  True False False  True]
bool


## 3.调整数组的数据类型 astype('int32')

In [13]:
t6 = t5.astype('int8')
print(t6)
print(t6.dtype)

[1 0 1 0 0 1]
int32


## 4.numpy中的小数 

In [15]:
import random
t7 = np.array([random.random() for i in range(10)])
print(t7)
print(t7.dtype)

[0.23028121 0.93312294 0.93261646 0.99355853 0.13312151 0.10877064
 0.36181591 0.85214529 0.40428986 0.01298672]
float64


### 5.np.round(a, decimals=0) 
decimal保留小数的位数

In [20]:
t8 = np.round(t7,decimals = 2)  #对t7保留两位小数，和python内置的方法一样
print(t8)

[0.23 0.93 0.93 0.99 0.13 0.11 0.36 0.85 0.4  0.01]


# np.ones（shape，dtype = None，order ='C' ）
### 创建一个由1组成的数组

In [3]:
a = np.ones((3,2))
print(a)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


# np.empty
### 函数empty创建一个数组，其初始内容是随机的，取决于内存的状态

In [38]:
a = np.empty((3,2))
print(a)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


# np.zeros
### 创建数组元素以 0 来填充的数组

In [21]:
# 默认为浮点数
a = np.zeros(5) 
print(a)

[0. 0. 0. 0. 0.]


# np.eye
### 创建对角线为1的方阵

In [3]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
