In [4]:
import numpy as np

## np.loadtxt(frame,dtype=np.float,delimiter=None,skiprows=0,usecols=None,unpack=False) 

#### frame        文件路径
#### dtype        以什么数据类型读入数组
#### delimiter  分割字符串，默认是任何空格
#### skiprows 跳过前x行，一般跳过第一行表头
#### usecols   读取指定列
#### unpack    如果为True，转置

In [11]:
us_file_path = './youtube_video_data/US_video_data_numbers.csv'
uk_file_path = './youtube_video_data/GB_video_data_numbers.csv'

In [13]:
t1 = np.loadtxt(us_file_path,delimiter=',',dtype='int')
print(t1)

[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [12]:
t2 = np.loadtxt(us_file_path,delimiter=',',dtype='int',unpack=True)
print(t2)

[[4394029 7860119 5845909 ...  142463 2162240  515000]
 [ 320053  185853  576597 ...    4231   41032   34727]
 [   5931   26679   39774 ...     148    1384     195]
 [  46245       0  170708 ...     279    4737    4722]]
