In [9]:
import numpy as np

# 转置 

In [3]:
t1 = np.arange(24).reshape((4,6))
print(t1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
print(t1.transpose())

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [5]:
print(t1.T)

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [8]:
'''
ndarray.swapaxes(1,0),通过交换轴进行转置,未转置前是（1,0）
'''
print(t1.swapaxes(1,0))

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


# 索引和切片 

In [15]:
a = np.arange(24).reshape((8,3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


#### 获取某一行 

In [29]:
print(a[2])  #去第三行，索引从0开始
print(a[2,:]) #逗号前是行，后是列

[6 7 8]
[6 7 8]


#### 取连续多行 

In [19]:
print(a[3:])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


#### 取不连续多行 

In [20]:
print(a[[2,4,6]]) #中括号里面再加一个中括号

[[ 6  7  8]
 [12 13 14]
 [18 19 20]]


#### 取列 

In [28]:
print(a[:,0]) #取第一列

[ 0  3  6  9 12 15 18 21]


#### 取连续多列 

In [31]:
print(a[:,1:]) #取第二列开始的连续多列

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]
 [16 17]
 [19 20]
 [22 23]]


#### 取不连续多列 

In [37]:
print(a)
print('--'*20)
print(a[:,[0,2]])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
----------------------------------------
[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]
 [12 14]
 [15 17]
 [18 20]
 [21 23]]


#### 取某个位置元素

In [33]:
#取第二行，第三列的值
print(a[1,2])

5


#### 取多行多列 

In [36]:
#取3到5行，2到3列
print(a)
print('--'*20)
print(a[2:5,1:3])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
----------------------------------------
[[ 7  8]
 [10 11]
 [13 14]]


#### 取多个不相邻的点 

In [40]:
print(a[[0,2],[0,1]])  #取(0,0),(2,1)
print(a[[1],[2]])  #去单个点,可直接a[1,2]

[0 7]
[5]
