In [21]:
import numpy as np

In [9]:
t = np.arange(24).reshape((4,6))
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [3]:
print(t[:,2:4])

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]


In [4]:
t[:,2:4] = 0
print(t)

[[ 0  1  0  0  4  5]
 [ 6  7  0  0 10 11]
 [12 13  0  0 16 17]
 [18 19  0  0 22 23]]


### 将t中小于10的值替换为3 (bool索引)

In [12]:
t = np.arange(24).reshape((4,6))
print(t<10)

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [13]:
t[t<10] = 3
print(t)

[[ 3  3  3  3  3  3]
 [ 3  3  3  3 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [14]:
print(t[t<10])

[3 3 3 3 3 3 3 3 3 3]


### numpy中的三元运算符
### np.where()

In [16]:
t = np.arange(24).reshape((4,6))
t = np.where(t<10,0,10)  #将t<10的赋值为0，否则赋值为10
print(t)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


### np.clip()


In [22]:
t = np.arange(24).reshape((4,6))
t = t.clip(10,18)  #将小于10的替换为10，大于18的替换为18
print(t)

[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]


### np.nan 

In [23]:
t = t.astype(float)
t[3,3] = np.nan  #要float类型才能修改值为nan
print(t)

[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 18. 18. nan 18. 18.]]


### np.count_nonzero() 

In [24]:
t[:,0] = 0
print(t)

[[ 0. 10. 10. 10. 10. 10.]
 [ 0. 10. 10. 10. 10. 11.]
 [ 0. 13. 14. 15. 16. 17.]
 [ 0. 18. 18. nan 18. 18.]]


In [25]:
print(np.count_nonzero(t))  #统计不为零的元素的个数

20


In [28]:
print(t!=t)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [27]:
print(np.count_nonzero(t!=t))  #统计nan的个数

1


### np.isnan() 

In [29]:
print(np.isnan(t))

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [32]:
print(np.count_nonzero(np.isnan(t)))  #通过np.isnan()判断nan的个数

1
