In [2]:
import numpy as np

# np.vstack((ndarray1,ndarray2))  竖直拼接
# np.hstack((ndarray1,ndarray2))  水平拼接

In [4]:
t1 = np.arange(12).reshape((2,6))
t2 = np.arange(12,24).reshape((2,6))
print(t1)
print(t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [7]:
print(np.vstack((t1,t2)))   #竖直拼接

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [8]:
print(np.hstack((t1,t2)))  #水平拼接

[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


# 数组的行列交换 

In [9]:
t = np.arange(12,24).reshape((3,4))
print(t)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [14]:
print(t[[1,2],:])

[[16 17 18 19]
 [20 21 22 23]]


In [15]:
#将第二行和第三行交换位置
t[[1,2],:] = t[[2,1],:]
print(t)

[[12 13 14 15]
 [20 21 22 23]
 [16 17 18 19]]


In [16]:
print(t[:,[0,2]])

[[12 14]
 [20 22]
 [16 18]]


In [17]:
#将第一列和第三列进行交换
t[:,[0,2]] = t[:,[2,0]]
print(t)

[[14 13 12 15]
 [22 21 20 23]
 [18 17 16 19]]
