In [1]:
import numpy as np

In [2]:
t = np.eye(4)
print(t)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### np.argmax(t,axis)
##### 获得当前方向上第一个最大值所在位置

In [5]:
print(np.argmax(t,axis=0))

[0 1 2 3]


### np.argmin(t,axis)
##### 获得当前方向上第一个最小值所在位置

In [7]:
print(np.argmin(t,axis=0))

[1 0 0 0]


# numpy生成随机数 

##### np.random.rand(d0,d1,d2,......dn)                    创建d0-dn维度的均匀分布的随机数数组，浮点数，范围从0-1
##### np.random.randn(d0,d1,d2,......dn)                 创建d0-dn维度的标准正态分布随机数，浮点数，平均数为0，标准差为1
##### np.random.randint(low,high,(shape))            从给定上下限范围选取随机数整数，范围是low-high，形状是shape
##### np.random.uniform(low,high,(size))              产生具有均匀分布的数组，low起始值，high结束值，size形状
##### np.random.normal(loc,scale,(size))              从指定正态分布中随机抽取样本，分布中心是loc（均值），标准差是scale，形状是size
##### np.random.seed(s)                                         随机数种子，通过设定相同的随机数种子，可以产生相同的随机数

# numpy中的复制 

##### a=b 完全不复制，a和b相互影响
##### a = b[:],视图的操作，一种切片，会创建新的对象a，但是a的数据完全由b保管，他们两个的数据变化是一致的，
##### a = b.copy(),复制，a和b互不影响


# numpy中常用统计函数

###### 求和：t.sum(axis=None)
###### 均值：t.mean(a,axis=None)  受离群点的影响较大
###### 中值：np.median(t,axis=None) 
###### 最大值：t.max(axis=None) 
###### 最小值：t.min(axis=None)
###### 极值：np.ptp(t,axis=None) 即最大值和最小值只差
###### 标准差：t.std(axis=None) 

In [8]:
t = np.arange(24).reshape(4,6)
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:
print(t.sum())   #也可用np.sum(t)
print(t.sum(axis=0))

276
[36 40 44 48 52 56]


In [13]:
print(t.mean(axis = 0))  #也可用np.mean(t)
print(np.mean(t,axis=0))

[ 9. 10. 11. 12. 13. 14.]
[ 9. 10. 11. 12. 13. 14.]


In [12]:
print(np.median(t,axis=0))

[ 9. 10. 11. 12. 13. 14.]


In [14]:
print(np.ptp(t,axis=0))

[18 18 18 18 18 18]


In [17]:
print(t.std(axis=0))  #也可用np.std(t)
print(np.std(t,axis=0))

[6.70820393 6.70820393 6.70820393 6.70820393 6.70820393 6.70820393]
[6.70820393 6.70820393 6.70820393 6.70820393 6.70820393 6.70820393]
