# 将数组中含nan的元素替换为其他元素 

In [1]:
import numpy as np

In [27]:
t1 = np.arange(12).reshape((3,4)).astype(float)
t1[1,2:] = np.nan
print(t1)

[[ 0.  1.  2.  3.]
 [ 4.  5. nan nan]
 [ 8.  9. 10. 11.]]


In [28]:
def fill_ndarray(t1):
#判断哪一列有nan
    for i in range(t1.shape[1]):
        temp_col = t1[:,i]  #获取每一列
        nan_num = np.count_nonzero(np.isnan(temp_col)) #获取当前一列nan个数
        if nan_num != 0:  #如果nan_num不为0，说明当前列有nan
            temp_not_nan_col = temp_col[temp_col==temp_col]  #获得当前一列不为nan的元素
            temp_col[np.isnan(temp_col)] = np.mean(temp_not_nan_col) #选中当前为nan的位置，把mean值赋值过去
    return t1

In [29]:
print(t1)
t1 = fill_ndarray(t1)
print(t1)

[[ 0.  1.  2.  3.]
 [ 4.  5. nan nan]
 [ 8.  9. 10. 11.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
